app_reporting:
    path: /
    defaults: {_controller: AppBundle:Reporting:reporting}

app_save_reporting:
    path: /save
    defaults: {_controller: AppBundle:Reporting:saveReportingAjax}

app_add_profile:
    path: /add-profile
    defaults: {_controller: AppBundle:Reporting:addProfile}
